---
title: "Classification avec FactoMineR sur les données du cours"
author: "François Husson"
output:
  pdf_document:
    fig_height: 6
    keep_tex: yes
  word_document: default
---

Script et sorties R permettant de retrouver les graphes et sorties du cours.
Le jeu de données doit être téléchargé et sauvegardé dans un répertoire connu (dans mon cas, le fichier a été sauvegardé dans le répertoire C:/husson).

```{r}
library(FactoMineR)
```

# Importation des données
```{r eval=FALSE}
setwd("C:/users/husson/")   # permet de placer la session R où se trouve le jeu de données
temperature <- read.table("AnaDo_JeuDonnees_TemperatFrance.csv",
        header=TRUE, sep=";", dec=".", row.names=1, fileEncoding="latin1")
```

```{r echo=FALSE}
temperature <- read.table("C:/Users/husson/Documents/home/huss/Enseign/cours/Films/Mooc_anado/Donnees/AnaDo_JeuDonnees_TemperatFrance.csv",
        header=TRUE, sep=";", dec=".", row.names=1, fileEncoding="latin1")
```
```{r}
summary(temperature)
```
# L'ACP
```{r eval=FALSE}
res <- PCA(temperature, quanti.sup=13:16,quali.sup=17)
```
```{r echo=FALSE}
res <- PCA(temperature, quanti.sup=13:16,quali.sup=17, graph=FALSE)
plot(res,cex=.7)
```
```{r echo=FALSE}
plot(res,choix="var",cex=.7)
```

# Construction de la classification ascendante hiérarchique
```{r echo=FALSE}
res.hcpc <- HCPC(res,  graph=FALSE, nb.clust=-1)
```

```{r eval=FALSE}
res.hcpc <- HCPC(res)
```

```{r echo=FALSE}
plot(res.hcpc,choice="tree")
```
```{r echo=FALSE}
plot(res.hcpc,choice="3D.map")
```
```{r echo=FALSE}
plot(res.hcpc,choice="map",draw.tree=FALSE)
```

# Résultats de la classification
```{r}
names(res.hcpc)
res.hcpc$data.clust
res.hcpc$desc.var
res.hcpc$desc.axes
res.hcpc$desc.ind
```
